// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClsR8qjJVPMSNyCOZsjhU_GgONJ1CCCI4',
    appId: '1:163240090481:web:f586a727129111e512f4d0',
    messagingSenderId: '163240090481',
    projectId: 'wethinkblogs-27aa8',
    authDomain: 'wethinkblogs-27aa8.firebaseapp.com',
    storageBucket: 'wethinkblogs-27aa8.appspot.com',
    measurementId: 'G-B103B0XBKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXoADDsg0cfs45bc4dVXZGA8kKK0zClZw',
    appId: '1:163240090481:android:f7f1477f5b9b4bc812f4d0',
    messagingSenderId: '163240090481',
    projectId: 'wethinkblogs-27aa8',
    storageBucket: 'wethinkblogs-27aa8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzNcvoE09eisgocOZ5y9jsfsGFbsT0sLs',
    appId: '1:163240090481:ios:f51a26fe4f9d6bb612f4d0',
    messagingSenderId: '163240090481',
    projectId: 'wethinkblogs-27aa8',
    storageBucket: 'wethinkblogs-27aa8.appspot.com',
    iosClientId: '163240090481-4qa65tfunbpj5ujhhouv72prju516ba0.apps.googleusercontent.com',
    iosBundleId: 'za.co.katlego.blogit',
  );
}
